package vista;

import java.awt.Canvas;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author HikingCarrot7
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    public VistaPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelResumen = new javax.swing.JScrollPane();
        tablaResumen = new javax.swing.JTable();
        panelLlegada = new javax.swing.JScrollPane();
        tablaLlegada = new javax.swing.JTable();
        simulacion = new javax.swing.JButton();
        esquema = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelResumen.setMaximumSize(new java.awt.Dimension(220, 525));
        panelResumen.setMinimumSize(new java.awt.Dimension(220, 525));
        panelResumen.setPreferredSize(new java.awt.Dimension(220, 525));

        tablaResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaResumen.setMaximumSize(new java.awt.Dimension(220, 525));
        tablaResumen.setMinimumSize(new java.awt.Dimension(220, 525));
        tablaResumen.setPreferredSize(new java.awt.Dimension(220, 525));
        tablaResumen.getTableHeader().setReorderingAllowed(false);
        panelResumen.setViewportView(tablaResumen);

        getContentPane().add(panelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        panelLlegada.setMaximumSize(new java.awt.Dimension(155, 525));
        panelLlegada.setMinimumSize(new java.awt.Dimension(155, 525));
        panelLlegada.setPreferredSize(new java.awt.Dimension(155, 525));

        tablaLlegada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Title 1", "Title 2"
            }
        ));
        tablaLlegada.setMaximumSize(new java.awt.Dimension(155, 525));
        tablaLlegada.setMinimumSize(new java.awt.Dimension(155, 525));
        tablaLlegada.setPreferredSize(new java.awt.Dimension(155, 525));
        panelLlegada.setViewportView(tablaLlegada);

        getContentPane().add(panelLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 35, -1, -1));

        simulacion.setText("Iniciar simulación.");
        simulacion.setMaximumSize(new java.awt.Dimension(155, 25));
        simulacion.setMinimumSize(new java.awt.Dimension(155, 25));
        simulacion.setPreferredSize(new java.awt.Dimension(155, 25));
        getContentPane().add(simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 5, -1, -1));

        esquema.setMaximumSize(new java.awt.Dimension(580, 525));
        esquema.setMinimumSize(new java.awt.Dimension(580, 525));
        esquema.setPreferredSize(new java.awt.Dimension(580, 525));
        getContentPane().add(esquema, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 35, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getPanelResumen()
    {
        return panelResumen;
    }

    public JScrollPane getPanelLlegada()
    {
        return panelLlegada;
    }

    public JButton getSimulacion()
    {
        return simulacion;
    }

    public JTable getTablaLlegada()
    {
        return tablaLlegada;
    }

    public JTable getTablaResumen()
    {
        return tablaResumen;
    }

    public Canvas getEsquema()
    {
        return esquema;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas esquema;
    private javax.swing.JScrollPane panelLlegada;
    private javax.swing.JScrollPane panelResumen;
    private javax.swing.JButton simulacion;
    private javax.swing.JTable tablaLlegada;
    private javax.swing.JTable tablaResumen;
    // End of variables declaration//GEN-END:variables
}
