package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author HikingCarrot7
 */
public class VistaPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelResumen = new javax.swing.JScrollPane();
        tablaResumen = new javax.swing.JTable();
        soporteEsquema = new javax.swing.JDesktopPane();
        esquema = new javax.swing.JInternalFrame();
        panelLlegada = new javax.swing.JScrollPane();
        tablaLlegada = new javax.swing.JTable();
        simulacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelResumen.setMaximumSize(new java.awt.Dimension(220, 525));
        panelResumen.setMinimumSize(new java.awt.Dimension(220, 525));
        panelResumen.setPreferredSize(new java.awt.Dimension(220, 525));

        tablaResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaResumen.setMaximumSize(new java.awt.Dimension(220, 525));
        tablaResumen.setMinimumSize(new java.awt.Dimension(220, 525));
        tablaResumen.setPreferredSize(new java.awt.Dimension(220, 525));
        tablaResumen.getTableHeader().setReorderingAllowed(false);
        panelResumen.setViewportView(tablaResumen);

        getContentPane().add(panelResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 35, -1, -1));

        esquema.setVisible(true);

        javax.swing.GroupLayout esquemaLayout = new javax.swing.GroupLayout(esquema.getContentPane());
        esquema.getContentPane().setLayout(esquemaLayout);
        esquemaLayout.setHorizontalGroup(
            esquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        esquemaLayout.setVerticalGroup(
            esquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        soporteEsquema.setLayer(esquema, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout soporteEsquemaLayout = new javax.swing.GroupLayout(soporteEsquema);
        soporteEsquema.setLayout(soporteEsquemaLayout);
        soporteEsquemaLayout.setHorizontalGroup(
            soporteEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esquema)
        );
        soporteEsquemaLayout.setVerticalGroup(
            soporteEsquemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(esquema)
        );

        getContentPane().add(soporteEsquema, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 35, 580, 525));

        panelLlegada.setMaximumSize(new java.awt.Dimension(155, 525));
        panelLlegada.setMinimumSize(new java.awt.Dimension(155, 525));
        panelLlegada.setPreferredSize(new java.awt.Dimension(155, 525));

        tablaLlegada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Title 1", "Title 2"
            }
        ));
        tablaLlegada.setMaximumSize(new java.awt.Dimension(155, 525));
        tablaLlegada.setMinimumSize(new java.awt.Dimension(155, 525));
        tablaLlegada.setPreferredSize(new java.awt.Dimension(155, 525));
        panelLlegada.setViewportView(tablaLlegada);

        getContentPane().add(panelLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 35, -1, -1));

        simulacion.setText("Iniciar simulación.");
        simulacion.setMaximumSize(new java.awt.Dimension(155, 25));
        simulacion.setMinimumSize(new java.awt.Dimension(155, 25));
        simulacion.setPreferredSize(new java.awt.Dimension(155, 25));
        getContentPane().add(simulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 5, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getPanelResumen()
    {
        return panelResumen;
    }

    public JDesktopPane getSoporteEsquema()
    {
        return soporteEsquema;
    }

    public JInternalFrame getEsquema()
    {
        return esquema;
    }

    public void setEsquema(JInternalFrame esquema)
    {
        this.esquema = esquema;
    }

    public JScrollPane getPanelLlegada()
    {
        return panelLlegada;
    }

    public JButton getSimulacion()
    {
        return simulacion;
    }

    public JTable getTablaLlegada()
    {
        return tablaLlegada;
    }

    public JTable getTablaResumen()
    {
        return tablaResumen;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame esquema;
    private javax.swing.JScrollPane panelLlegada;
    private javax.swing.JScrollPane panelResumen;
    private javax.swing.JButton simulacion;
    private javax.swing.JDesktopPane soporteEsquema;
    private javax.swing.JTable tablaLlegada;
    private javax.swing.JTable tablaResumen;
    // End of variables declaration//GEN-END:variables
}
